services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    ports:
      - "5672:5672"     # Porta para comunicação com aplicativos
      - "15672:15672"   # Porta da interface web de gerenciamento
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: 123456
    networks:
        - shared_network
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: unless-stopped

  postgres:
    image: postgres:15
    container_name: postgres-hospital
    restart: always
    environment:
      POSTGRES_DB: ghospital
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    networks:
      - shared_network
    volumes:
      - pgdata:/var/lib/postgresql/data

  app:
    build: .
    container_name: spring-ghospital
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/ghospital
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
    networks:
      - shared_network

volumes:
  pgdata:
  rabbitmq_data:

networks:
  shared_network:
    name: tech_shared_network
    external: false
    driver: bridge
